controller:
  # Enable ingress class resource as default one
  ingressClassResource:
    default: true
  # Enable configuration at ingress level
  allowSnippetAnnotations: true
  # Configmap for nginx
  config:
    # Enable brotli compression
    enable-brotli: "true"
    # Declare a static cache block to be used in ingresses
    # And enable nginx status endpoint, see https://github.com/DataDog/integrations-core/tree/master/nginx_ingress_controller
    http-snippet: |
      # Declare a static cache block to be used in ingresses
      proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=static-cache:10m max_size=10g inactive=60m use_temp_path=off;
      # Expose nginx status endpoint
      server {
        listen 18080;

        location /nginx_status {
          allow all;
          stub_status on;
        }

        location / {
          return 404;
        }
      }
    # Restore pre 1.12 default value
    # @see https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#annotations-risk-level
    # @see https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations-risk/
    # @see https://ellie.wtf/notes/ingress-nginx-risky-annotations
    annotations-risk-level: Critical
  # Used in newrelic to report queuing time metric
  proxySetHeaders:
    X-Request-Start: t=${msec}
