name: Install Kind and configure a Kubernetes cluster
description: Create a cluster and a kubeconfig file in workspace
inputs:
  cluster_name:
    description: 'Name of the Kubernetes cluster'
    default: 'kind'
  config:
    description: 'Path to the kind configuration file'
    default: '.github/kind-config.yml'
  version:
    description: 'Version of the Kubernetes cluster'
    default: '1.31.0'

runs:
  using: "composite"
  steps:
    - name: Setup Kubernetes
      uses: helm/kind-action@v1
      with:
        cluster_name: ${{ inputs.cluster_name }}
        config: ${{ inputs.config }}
        node_image: "kindest/node:v${{ inputs.version }}"
