name: Install Kind and configure a Kubernetes cluster
description: Create a cluster and a kubeconfig file in workspace
inputs:
  cluster_name:
    description: 'Name of the Kubernetes cluster'
    default: 'kind'
  config:
    description: 'Path to the kind configuration file'
    default: '.github/kind-config.yml'
  version:
    description: 'Kind action version'
    default: 'v1'

runs:
  using: "composite"
  steps:
    - name: Setup Kubernetes
      uses: helm/kind-action@${{ inputs.version }}
      with:
        cluster_name: ${{ inputs.cluster_name }}
        config: ${{ inputs.config }}
