name: Lint Actions

on:
  push:
    paths:
      - '.github/workflows/**.*'

# This job will validate that every change to the .github/workflows directory uses a valid Github Actions syntax.
# It will run only when a change is pushed to the .github/workflows directory so it doesn't impact our usage of minutes.
# To run it locally install actionlint and shellcheck and simplu run `actionlint` in the repo
# In OsX is simple as `brew install actionlint shellcheck`
jobs:
  actionlint:
    name: Lint Github Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-check
          fail_on_error: true
