name: Terraform check

on:
  push:
    paths:
      - '**/*.tf'

jobs:
  terraform:
    name: Terraform check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        run: terraform fmt -check -recursive
